import type { Metadata } from "next";
import "./globals.css";
import { MathJaxContext } from "better-react-mathjax";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const config = {
  loader: { load: ["input/asciimath"] },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <MathJaxContext config={config}>
        <body>{children}</body>
      </MathJaxContext>
    </html>
  );
}
