import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MathJaxContext } from "better-react-mathjax";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const config = {
  loader: { load: ["input/asciimath"] },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <MathJaxContext config={config}>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>{children}</body>
      </MathJaxContext>
    </html>
  );
}
